#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install gqrx
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries for GQRX (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - cmake
      - libqt5svg5-dev
      - gnuradio-dev
      - libpulse-dev
      - pavucontrol
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries for GQRX (ARM Buster)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - qt5-default
      - libgnuradio-osmosdr0.1.4
      - libgnuradio-iqbalance3.7.11
    when: is_arm|bool and is_buster|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries for GQRX (ARM Bullseye)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - qtbase5-dev
      - libgnuradio-osmosdr0.2.0
      - libgnuradio-iqbalance3.8.0
    when: is_arm|bool and is_bullseye|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries for GQRX (Xubuntu)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libgnuradio-osmosdr0.2.0
      - libgnuradio-iqbalance3.8.0
    when: is_hampc|bool and is_impish|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries for GQRX (Jammy)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - qtbase5-dev
      - libgnuradio-osmosdr0.2.0
      - libgnuradio-iqbalance3.9.0
    when: is_hampc|bool and is_jammy|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download GQRX sources
    git:
      repo: https://github.com/csete/gqrx.git
      dest: /home/{{ ham_user }}/hamradio/gqrx-source
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory gqrx-source/build
    file:
      path: /home/{{ ham_user }}/hamradio/gqrx-source/build
      state: directory

  - name: Modify categories for gqrx.desktop
    become: yes
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/gqrx-source/dk.gqrx.gqrx.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio SDR

  - name: Build GQRX CMakeFiles
    command: cmake --install-prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/gqrx-source/build

  - name: Build GQRX
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/gqrx-source/build

  - name: Install GQRX
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/gqrx-source/build

  - name: Install GQRX desktop
    become: yes
    command: cp dk.gqrx.gqrx.desktop /usr/local/share/applications/gqrx.desktop
    args:
      chdir: /home/{{ ham_user }}/hamradio/gqrx-source

  - name: Remove GQRX build directory
    file:
      path: /home/{{ ham_user }}/hamradio/gqrx-source
      state: absent

  # gnuradio-grc.desktop is from the gnuradio dpkg but it
  # isn't installed directly. Instead it is installed as a
  # dependency of gnuradio-dev which is installed above.
  - name: Modify categories for gnuradio-grc.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/gnuradio-grc.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio
