#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install hamlib
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

    - name: Create directory hamradio
      file:
        path: /home/{{ ham_user }}/hamradio
        state: directory

    - name: Install dependent libraries (Raspberry Pi Buster)
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python
        - python-dev
      when: is_rpi|bool and is_buster|bool
      retries: 5
      delay: 30
      register: result

    - name: Install dependent libraries (Raspberry Pi Bullseye)
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - libnova-dev
        - libindi-dev
      when: is_rpi|bool and is_bullseye|bool
      retries: 5
      delay: 30
      register: result
      until: result.failed == false

    - name: Install dependent libraries (Jammy)
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-dev
        - libnova-dev
        - libindi-dev
      when: is_jammy|bool
      retries: 5
      delay: 30
      register: result
      until: result.failed == false

    - name: Install dependent libraries (Inovato)
      become: yes
      package:
        name: python3-dev
        state: present
      when: is_iq|bool
      retries: 5
      delay: 30
      register: result

    - name: Install dependent libraries (Common)
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - git
        - libtool
        - libfltk1.3-dev
        - libsamplerate0-dev
        - portaudio19-dev
        - libsndfile1-dev
        - libxft-dev
        - libxinerama-dev
        - libxcursor-dev
        - libpulse-dev
        - pavucontrol
        - swig
        - libusb-1.0-0-dev
        - libreadline-dev
        - libxml2-dev
        - libgd-dev
      retries: 5
      delay: 30
      register: result
      until: result.failed == false

    - name: Git clone latest Hamlib sources
      git:
        repo: https://github.com/Hamlib/Hamlib.git
        dest: /home/{{ ham_user }}/hamradio/hamlib
      retries: 5
      delay: 30
      register: result
      until: result.failed == false

    - name: Bootstrap Hamlib
      command: ./bootstrap
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib

    - name: Configure Hamlib (Buster)
      command: ./configure --with-python-binding --with-xml-support
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib
      when: is_buster|bool and not is_jammy|bool

    - name: Configure Hamlib (Bullseye)
      command: ./configure PYTHON_VERSION='3.9' --with-python-binding --with-xml-support
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib
      when: is_bullseye|bool or is_iq|bool and not is_buster|bool and not is_jammy|bool

    - name: Configure Hamlib (Bookworm)
      command: ./configure PYTHON_VERSION='3.11' --with-python-binding --with-xml-support
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib
      when: is_bookworm|bool

    - name: Configure Hamlib (Jammy)
      command: ./configure PYTHON_VERSION='3.10' --with-python-binding --with-xml-support
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib
      when: is_jammy|bool

    - name: Build Hamlib
      command: make all
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib

    - name: Install Hamlib
      become: yes
      command: make install
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib

    - name: Build Hamlib Python bindings
      command: make
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib/bindings

    - name: Install Hamlib Python bindings
      become: yes
      command: make install
      args:
        chdir: /home/{{ ham_user }}/hamradio/hamlib/bindings

    - name: Configure dynamic linker run-time bindings
      become: yes
      command: ldconfig

    - name: Remove Hamlib build directory
      file:
        path: /home/{{ ham_user }}/hamradio/hamlib
        state: absent
