#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install wfview - a program to control modern Icom ham radios
  hosts: all
  gather_facts: no
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - git
      - qt5-qmake
      - libqt5core5a
      - qtbase5-dev
      - libqt5serialport5
      - libqt5serialport5-dev
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - qtmultimedia5-dev
      - libqcustomplot-doc
      - libqcustomplot-dev
      - libopus-dev
      - libeigen3-dev
      - libqt5gamepad5
      - libqt5gamepad5-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (ARM Buster or Bullseye)
    become: yes
    package:
      name: libqcustomplot2.0
      state: present
    when: is_arm|bool and (is_buster|bool or is_bullseye|bool)
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (ARM Buster)
    become: yes
    package:
      name: qt5-default
      state: present
    when: is_arm|bool and is_buster|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (ARM Bookworm)
    become: yes
    package:
      name: libqcustomplot2.1
      state: present
    when: is_arm|bool and is_bookworm|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Git clone latest wfview sources
    git:
      repo: https://gitlab.com/eliggett/wfview.git
      dest: /home/{{ ham_user }}/hamradio/wfview
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory build
    file:
      path: /home/{{ ham_user }}/hamradio/build
      state: directory

  - name: Rewrite RtAudio include directory for rthandler.h
    replace:
      path: /home/{{ ham_user }}/hamradio/wfview/rthandler.h
      regexp: '#include "rtaudio/RtAudio.h"'
      replace: '#include "RtAudio.h"'

  - name: Rewrite RtAudio include directories servermain.h
    replace:
      path: /home/{{ ham_user }}/hamradio/wfview/servermain.h
      regexp: '#include "rtaudio/RtAudio.h"'
      replace: '#include "RtAudio.h"'

  - name: Rewrite RtAudio include directories audiodevices.h
    replace:
      path: /home/{{ ham_user }}/hamradio/wfview/audiodevices.h
      regexp: '#include "rtaudio/RtAudio.h"'
      replace: '#include "RtAudio.h"'

  - name: Rewrite RtAudio include directories wfmain.h
    replace:
      path: /home/{{ ham_user }}/hamradio/wfview/wfmain.h
      regexp: '#include "rtaudio/RtAudio.h"'
      replace: '#include "RtAudio.h"'

  - name: Rewrite wfview project install prefix
    replace:
      path: /home/{{ ham_user }}/hamradio/wfview/wfview.pro
      regexp: '  PREFIX = /usr/local'
      replace: '  PREFIX = /usr'

  - name: Build wfview Makefiles
    command: qmake ../wfview/wfview.pro
    args:
      chdir: /home/{{ ham_user }}/hamradio/build

  - name: Build wfview
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/build

  - name: Install wfview
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/build

  - name: Modify categories for wfview.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/wfview.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio

  - name: Remove wfview source directories
    file:
      path: /home/{{ ham_user }}/hamradio/{{ item }}
      state: absent
    with_items:
      - wfview
      - build
