#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Chirp Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio/
      state: directory

  - name: Install Chirp prerequisite packages (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - python3-wxgtk4.0
      - python3-serial
      - python3-six
      - python3-future
      - python3-requests
      - python3-pip
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Determine latest version of Chirp Next on web
    shell: curl --silent "https://trac.chirp.danplanet.com/chirp_next/" | grep -Po "next-[0-9]+" | grep -Po "[0-9]+" | head -n 1
    args:
      warn: no
    retries: 5
    delay: 30
    register: download_version
    until: download_version.failed == false

  - name: Install Chirp {{ download_version.stdout }}
    command: pip3 install --break-system-packages https://trac.chirp.danplanet.com/chirp_next/next-{{ download_version.stdout }}/chirp-{{ download_version.stdout }}-py3-none-any.whl

#  - name: Modify categories for chirp.desktop
#    become: yes
#    lineinfile:
#      path: /usr/share/applications/chirp.desktop
#      regexp: '^Categories=.*'
#      line: Categories=HamRadio
